from openai import OpenAI
import os
import pickle
import base64
import json
import random
import json
client = OpenAI()

img_root = "/home/liuxiao/TuringGithub/XiaoData/coco_val_set_color_det"



# Function to encode the image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

path = '/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/groundtruths_d_colorest.json'
with open(path) as f:
    groundtruths_d_colorest = json.load(f)

answers = {}
for fn, trials in groundtruths_d_colorest.items():
    # Path to your image
    # fn = "0235.jpg"
    image_path = os.path.join(img_root,fn)
    # Getting the Base64 string
    base64_image = encode_image(image_path)
    colorests = ' '.join(['{}. {}'.format(i+1, trial['response']) for i,trial in enumerate(trials)])
    color_prompt = '''Task: You will be given a scene image along with 4 corresponding dominant color estimation. Your goal is to determine whether each estimation was generated by a human or an AI model.\nInstructions: Please present answers as pairs consisting of the classification (either 'Human' or 'AI-generated') followed by a brief justification for your decision. At the end, include a section titled 'Summary of Classifications' that lists all classifications in order as a bullet list. \nEstimations: {}'''.format(colorests)
    response = client.chat.completions.create(
            model="chatgpt-4o-latest",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": color_prompt},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
                        },
                    ],
                }
            ],
            max_tokens=512,
        )
    ans = response.choices[0].message.content
    print("======"*20)
    print("[{}]".format(fn),[(trial['machine_groundtruth'],trial['response']) for trial in trials])
    print("[{}]".format(fn), color_prompt)
    print("[{}]".format(fn), response.choices[0])
    print(ans)
    answers[fn] = ans
        
    # break
with open('/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/chatgpt_color_estimation_zeroshot_judge.pkl', 'wb') as f:
    pickle.dump(answers,f)
with open('/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/chatgpt_color_estimation_zeroshot_judge.pkl', 'rb') as f:
    print(pickle.load(f))