from openai import OpenAI
import os
import pickle
import base64
import json
import random
import json
client = OpenAI()

img_root = "/home/liuxiao/TuringGithub/imagecaption/MturkExps/image_captioning_task/Data/imgset"



# Function to encode the image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

path = "/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/captions_d.json"
with open(path) as f:
    captions_d = json.load(f)

answers = {}
for fn,caps in captions_d.items():
    # Path to your image
    # fn = "0235.jpg"
    image_path = os.path.join(img_root,fn)
    # Getting the Base64 string
    base64_image = encode_image(image_path)
    
    captioning_prompt = '''Task: You will be given a scene image along with 7 corresponding captions. Your goal is to determine whether each caption was generated by a human or an AI model.\nInstructions: Please present answers as pairs consisting of the classification (either 'Human' or 'AI-generated') followed by a brief justification for your decision. At the end, include a section titled 'Summary of Classifications' that lists all classifications in order as a bullet list.\nCaptions: {}'''.format(caps)
    response = client.chat.completions.create(
            model="chatgpt-4o-latest",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": captioning_prompt},
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
                        },
                    ],
                }
            ],
            max_tokens=1024,
        )
    ans = response.choices[0].message.content
    print("======"*20)
    print("[{}]".format(fn), captioning_prompt)
    print("[{}]".format(fn), response.choices[0])
    print(ans)
    answers[fn] = ans
        
    # break
with open('/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/chatgpt_image_captioning_zeroshot_judge.pkl', 'wb') as f:
    pickle.dump(answers,f)
with open('/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/chatgpt_image_captioning_zeroshot_judge.pkl', 'rb') as f:
    print(pickle.load(f))