from openai import OpenAI
import os
import pickle
import base64
import json
import random
import json
client = OpenAI()

# img_root = "/home/liuxiao/TuringGithub/XiaoData/coco_val_set_color_det"



# Function to encode the image
# def encode_image(image_path):
#     with open(image_path, "rb") as image_file:
#         return base64.b64encode(image_file.read()).decode("utf-8")

path = '/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/groundtruths_d_wordassoc.json'
with open(path) as f:
    groundtruths_d_wordassoc = json.load(f)

answers = {}
for fn, trials in groundtruths_d_wordassoc.items():
    # # Path to your image
    # # fn = "0235.jpg"
    # image_path = os.path.join(img_root,fn)
    # # Getting the Base64 string
    # base64_image = encode_image(image_path)
    cue = trials[0]['cueWord']
    wordassocs = ' '.join(['{}. {}'.format(i+1, trial['response']) for i,trial in enumerate(trials)])
    word_prompt = '''Task: You will be given a target word along with 10 associated words. Your goal is to determine whether each associated word was generated by a human or an AI model. The target word is the central concept, and each associated word is generated independently and intended to be related to it. \nInstructions: Please present answers as pairs consisting of the classification (either 'Human' or 'AI-generated') followed by a brief justification for your decision. At the end, include a section titled 'Summary of Classifications' that lists all classifications in order as a bullet list.\nTarget Word: {} \nAssociated Words: {}'''.format(cue,wordassocs)
    response = client.chat.completions.create(
            model="chatgpt-4o-latest",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": word_prompt},
                    ],
                }
            ],
            max_tokens=1024,
        )
    ans = response.choices[0].message.content
    print("======"*20)
    print("[{}]".format(fn),[(trial['machine_groundtruth'],trial['response']) for trial in trials])
    print("[{}]".format(fn), word_prompt)
    print("[{}]".format(fn), response.choices[0])
    print(ans)
    answers[fn] = ans
        
    # break
with open('/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/chatgpt_wordassoc_zeroshot_judge.pkl', 'wb') as f:
    pickle.dump(answers,f)
with open('/home/liuxiao/TuringGithub/XiaoData/ZeroShotJudge/chatgpt_wordassoc_zeroshot_judge.pkl', 'rb') as f:
    print(pickle.load(f))